#! /bin/sh
# /usr/bin/ff-theme-util

# determine config to watch and method to query current gtk theme
get_config() {
    config="$HOME/.gtkrc-2.0"
    gtk3_conf="$HOME/.config/gtk-3.0/settings.ini"
    case $DESKTOP_SESSION in
        cinnamon) current_theme=$(gsettings get org.cinnamon.desktop.interface gtk-theme | tr -d \')
            ;;
        gnome) current_theme=$(gsettings get org.gnome.desktop.interface gtk-theme | tr -d \')
            ;;
        xfce) config="$HOME/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml"
            current_theme=$(xfconf-query -lvc xsettings -p /Net/ThemeName| cut -d' ' -f3)
            ;;
        *)  if [[ $gtk3_conf -nt $config ]]; then
                config=$gtk3_conf
                current_theme=$(grep "gtk-theme-name" $config | cut -d'=' -f2)
            else
                current_theme=$(grep "gtk-theme-name" $config | cut -d'"' -f2)
            fi
            ;;
    esac
}

# check if current theme provides chrome dir
has_chrome() {
    chromedir="$themesdir/$current_theme/chrome"
    [[ -e "$chromedir" ]] && return 0 || return 1
}

# create symlinks to chrome dir for each profile
set_theme() {
    for p in $(grep Path "$profiledir/profiles.ini" | cut -d'=' -f2); do
        ln -sfd "$1" "$profiledir/$p"
    done
}

update_theme() {
    get_config

    # Firefox
    profiledir="$HOME/.mozilla/firefox"
    themesdir="/usr/share/themes/Firefox"
    if has_chrome; then
        # in case we also need to use it for Palemoon
        has_ff=true
        ff_chromedir=$chromedir
        if [[ -e $profiledir ]]; then
            set_theme $chromedir
        fi
    else
        has_ff=false
    fi

    # Palemoon
    profiledir="$HOME/.moonchild productions/pale moon"
    themesdir="/usr/share/themes/Palemoon"
    if [[ -e $profiledir ]]; then
        if has_chrome; then
           set_theme $chromedir
        # fallback to Firefox theme if available
        elif [[ $has_ff == "true" ]]; then
           set_theme $ff_chromedir
        fi
    fi
}

get_config
update_theme

# watch for gtk2 theme changes
while inotifywait -e attrib $config; do
    update_theme
done

exit 0
