#!/bin/sh

##Template script for generate some empty file

#create a empty file in template directory
touch $(xdg-user-dir TEMPLATES)/Empty\ File

#create a empty file in template directory for bash script
touch $(xdg-user-dir TEMPLATES)/Empty\ Bash
echo "#!/bin/bash" > $(xdg-user-dir TEMPLATES)/Empty\ Bash

#create a empty file in template directory for .desktop
touch $(xdg-user-dir TEMPLATES)/Empty\ Desktop\ File.desktop
echo "[Desktop Entry]
Name=
Comment=
Keywords=
Exec=
TryExec=
Terminal=false
Icon=
Type=
Categories=
MimeType=
StartupNotify=false
StartupWMClass=
OnlyShowIn=
Actions=" > $(xdg-user-dir TEMPLATES)/Empty\ Desktop\ File.desktop

