EXTRAMODULES='extramodules-4.11-rt-MANJARO'

run_depmode() {
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
}

post_install() {
cat << EOF
===> You must load vboxdrv module before starting VirtualBox:
===> # modprobe vboxdrv
EOF
    run_depmode
}

post_upgrade() {
    run_depmode
    echo 'In order to use the new version, reload all virtualbox modules manually.'
}

post_remove() {
    run_depmode
}
