all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"
yellow="${bold}$(tput setaf 3)"

# Colored makepkg-like functions
msg_blue() {
  printf "${blue}==>${bold} $1${all_off}\n"
}

note() {
  printf "${blue}==>${yellow} NOTE:${bold} $1${all_off}\n"
}

post_install() {
  note "Custom flags should be put directly in: ~/.config/liri-flags.conf"
  note "The launcher is called: 'liri-browser'"
}

post_upgrade() {
  post_install
}
