#!/bin/sh
# /usr/bin/fix-trash

userid=$(id -u $USER)

if [ ! -d "/.Trash-$userid" ]; then
  printf "\n ==> Creating trash directories for user $(whoami)\n\n"
  sudo mkdir -p /.Trash-$userid/{expunged,files,info}
  sudo chown -R $userid /.Trash-$userid
else
  printf "\n ==> Trash directories for user $(whoami) are available.\n\n"
fi

exit 0
