post_install() {
  glib-compile-schemas --allow-any-name usr/share/glib-2.0/schemas
  update-desktop-database -q
  cd usr/share/backgrounds
  rm default_background.jpg 2>/dev/null
  ln -s /usr/share/backgrounds/grey_paper.jpg default_background.jpg
}

post_upgrade() {
	post_install
}

post_remove() {
  glib-compile-schemas --allow-any-name usr/share/glib-2.0/schemas
  update-desktop-database -q
}
