msg() {
ALL_OFF="\e[1;0m"
BOLD="\e[1;1m"
RED="${BOLD}\e[1;31m"
local mesg=$1; shift
printf "
${RED}==>${ALL_OFF} ${mesg}${ALL_OFF}\n" "$@" >&2
}

post_install() {
msg "Font, colour and your preferred terminal application for dmenu"
msg "can be defined in ~/.dmenurc"
}

post_upgrade() {
msg "dmenu can be configured in your ~/.dmenurc file.
    To change your preferred terminal command edit or add the variable
    TERMINAL_CMD= - for example: TERMINAL_CMD=\"lxterminal -e\"\n"
}
