#!/bin/sh

##Symple script to check if printing support is installed

#temporary workaround waiting next release

if pacman -Qi cups > /dev/null; then
   echo
   echo "Printing support installed"
   echo
else 
   echo
   echo "Printing support not installed, to enable please type this in a terminal"
   echo "sudo pacman -S manjaro-printer"
   echo "or install manjaro-printer pkg via pamac"
   echo
fi

exit 0

