#! /bin/bash
#
# bspwm-session
# From https://github.com/baskerville/bspwm/blob/master/contrib/freedesktop/bspwm-session , 
# modified to copy example configs unless user already has some.
# Later modified to drop multiuser support.
# This script is a session launcher for bspwm.
# It is based on similar scripts included with Openbox.

# Trap: make sure everything started in ~/.config/bspwm/autostart is
# signalled when this script exits or dies. Also clean up $state_path.
function on_exit {
	for child in $(jobs -p); do
		jobs -p | grep -q $child && kill $child
	done
	# Extra paranoia
	[[ -d "${state_path}" && -w "${state_path}" ]] && rm -rf -- "${state_path}"
}

trap on_exit EXIT SIGHUP SIGINT SIGTERM
#Create example configs if configs are not present
[[ ! -f /home/$(whoami)/.config/sxhkd/sxhkdrc ]] && cp /etc/skel/.config/sxhkd/sxhkdrc /home/$(whoami)/.config/sxhkd/sxhkdrc
[[ ! -f /home/$(whoami)/.config/bspwm/bspwmrc ]] && cp /etc/skel/.config/bspwm/bspwmrc /home/$(whoami)/.config/bspwm/bspwmrc
[[ ! -f /home/$(whoami)/.config/bspwm/autostart ]] && touch /home/$(whoami)/.config/bspwm/autostart
# Environment and autostart:
source_these=(
	"/etc/profile"
	"${HOME}/.profile"
	"${XDG_CONFIG_HOME:-"$HOME/.config"}/bspwm/autostart"
)

for file in "${source_these[@]}"; do
	[ -r "${file}" ] && . "${file}"
done

# Launch sxhkd:
[ -e /bin/dash ] && SXHKD_SHELL="/bin/dash"
sxhkd &
# Launch bspwm:
bspwm
