#!/usr/bin/sh
#
# maia color scheme for the console by @oberon
# Provided under the GNU General Public License
# as published by the Free Software Foundation.

TERM=linux

_color00='232423' # BLACK   | dark grey
_color08='282928'
_color01='BA2922' # RED
_color09='CC372C'
_color02='7E807E' # GREEN   | very bright grey
_color10='8D8F8D'
_color03='4C4F4D' # YELLOW  | grey
_color11='4E524F'
_color04='16A085' # BLUE    | turquoise, maia highlight
_color12='13BF9D'
_color05='43746A' # MAGENTA | bright grey
_color13='487D72'
_color06='00CCCC' # CYAN
_color14='00D1D1'
_color07='E0E0E0' # WHITE
_color15='E8E8E8'

echo -en "\e]P0$_color00"
echo -en "\e]P1$_color01"
echo -en "\e]P2$_color02"
echo -en "\e]P3$_color03"
echo -en "\e]P4$_color04"
echo -en "\e]P5$_color05"
echo -en "\e]P6$_color06"
echo -en "\e]P7$_color07"
echo -en "\e]P8$_color08"
echo -en "\e]P9$_color09"
echo -en "\e]Pa$_color10"
echo -en "\e]Pb$_color11"
echo -en "\e]Pc$_color12"
echo -en "\e]Pd$_color13"
echo -en "\e]Pe$_color14"
echo -en "\e]Pf$_color15"
