#!/bin/bash
# /usr/bin/fbmenu

## backup existing menu config

if [ -f ~/.config/fbmenugen/schema.pl ]
then
mv ~/.config/fbmenugen/schema.pl ~/.config/fbmenugen/schema.pl_backup
fi
if [ -f ~/.config/fbmenugen/config.pl ]
then
mv ~/.config/fbmenugen/config.pl ~/.config/fbmenugen/config.pl_backup
fi
if [ -f ~/.fluxbox/menu ]
then
mv ~/.fluxbox/menu ~/.fluxbox/menu_backup
fi

##copy new menu file and config for regenerate function

install -dm755 ~/.{config/fbmenugen,fluxbox}
install -m644 /etc/xdg/fbmenu-manjaro/{config,schema}.pl ~/.config/fbmenugen/
install -m644 /etc/xdg/fbmenu-manjaro/menu ~/.fluxbox/

##regenerate the new menu

fbmenugen
