post_install() {

msg() {
ALL_OFF="\e[1;0m"
BOLD="\e[1;1m"
GREEN="${BOLD}\e[1;32m"
local mesg=$1; shift
printf "${GREEN}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
}

if [ -e /etc/oblogout.conf ]; then
  msg "your existing oblogout.conf has been saved as /etc/oblogout.conf.bak"
  mv /etc/oblogout.conf /etc/oblogout.conf.bak
fi
cp etc/oblogout-manjaro.conf etc/oblogout.conf
}

post_upgrade() {
	post_install
}
