#! /bin/bash
MHWDSCRIPTNAME="video-catalyst"

## is it installed?
if [ ! -f "/var/lib/mhwd/local/pci/${MHWDSCRIPTNAME}" ]
    then
        echo "${MHWDSCRIPTNAME} is not installed"
        exit 1
fi

if [ "$(whoami)" != "root" ]
    then
        echo "this script needs root!"
        echo "$ pkexec catalystuninstall"
        exit 1
fi

mhwd -r pci ${MHWDSCRIPTNAME}
pacman --noconfirm -S xorg-server>=1.18 xf86-input-libinput

echo "done!"
exit 0
