#! /bin/bash
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
##
## This script should generate a List of PCI-IDs
## certain types of Graphicscardsgenerations
##
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
##
## Variables
##
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##

UPSTREAM_LISTFILE_URL="https://raw.githubusercontent.com/pciutils/pciids/master/pci.ids"
UPSTREAM_LISTFILE_LOCAL_PATH="/tmp/PCIIDLIST"

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
##
## functions
##
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##

function fn_checkinput()
{
        if [ ! ${OUTPUTFILE} ]
        then
            echo -e "This script requieres 3 inputs"
            echo -e "    -o\tan output file (this has to be the first option)"
            echo -e "    -q\tdont add comments to the pciid files(optional)"
            echo -e "    -a\tsets the name of the hardware generation (you can use this multiple times)"
            echo
            echo -e "usage:\n listgen -o /home/username/PCILIST -a polaris11 -a polaris10"
            exit 1
        fi
}

function fn_download()
{
    curl -o "${UPSTREAM_LISTFILE_LOCAL_PATH}" "${UPSTREAM_LISTFILE_URL}"
    if [ ! -f "${UPSTREAM_LISTFILE_LOCAL_PATH}" ] || ! grep "List of PCI ID's" "${UPSTREAM_LISTFILE_LOCAL_PATH}" > /dev/null
    then
        echo "Missing or wrong file in downloadpath"
        exit 1
    fi
    
    # extrackt AMD part
    ## remove everything before ^1002
    sed -i -n '/^1002/,$p' "${UPSTREAM_LISTFILE_LOCAL_PATH}"
    ## remove everything below ^1003
    sed -i '/^1003/,$d' "${UPSTREAM_LISTFILE_LOCAL_PATH}"
    ## remove comments
    sed -i '/^#/ d' "${UPSTREAM_LISTFILE_LOCAL_PATH}"
    ## remove sub-IDs
    sed -i 's/^\t//g' "${UPSTREAM_LISTFILE_LOCAL_PATH}"
    sed -i '/^\t/ d' "${UPSTREAM_LISTFILE_LOCAL_PATH}"
    
    echo -e "\n"
}

function fn_cleanfile()
{
    echo -e "##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##\n##\n## Created by listgen-script\n## https://github.com/Tids/mhwd-addon-amdgfx-hwe\n## do not edit\n##\n##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##" > "${OUTPUTFILE}"
}

function fn_copyover()
{
    if grep -wi " ${SETGEN}" ${UPSTREAM_LISTFILE_LOCAL_PATH} > /dev/null
    then
        if [ "${COMMENTSNO}" != "yes" ]
        then
            echo -e "\n##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##\n##\n## ${SETGEN}\n##\n##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##" >> "${OUTPUTFILE}"
        fi
        grep -wi " ${SETGEN}" "${UPSTREAM_LISTFILE_LOCAL_PATH}" | grep -vi "audio" | grep -v "#" | cut -d" " -f1 >> "${OUTPUTFILE}"
    fi
}

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
##
## run 'n fly
##
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##

fn_download
while getopts qo:a: opt
do
case $opt in
    o)
        OUTPUTFILE="${OPTARG}"
        fn_cleanfile
    ;;
    a)
        fn_checkinput
        SETGEN=$(echo "${OPTARG}" | awk '{print toupper($0)}')
        echo "+${SETGEN}"
        fn_copyover
    ;;
    q)
        COMMENTSNO="yes"
    ;;
esac
done
fn_checkinput
exit 0
