#!/bin/sh

##Monitor if wrapper is installed

while [ ! -f /.check-aur ]; do

	sleep 300

done

##Window for warning

#add time to prevent open window immediatly at boot

sleep 300

zenity --question --title="WARNING" --window-icon=warning.ico --text="\nFull access to AUR detected!\nIf you would like to learn more about AUR features and risks (!) press OK and you will be redirected to the Wiki page.\n\nIf you already know what AUR is press Cancel" --cancel-label="Cancel" --ok-label="Ok"  ;

    if [ $? == 1 ] ; then
         rm ~/.config/autostart/check-aur.desktop
         exit 0
    fi  

#Firefox open links in a tabs
      
xdg-open https://wiki.manjaro.org/index.php/Arch_User_Repository

#Inform user to read the page

zenity --question --text="Read this pages carefully before install AUR programs\nPress Yes to confirm that you have been informed about the risks of yaourt and AUR." ;
       
    if [ $? == 1 ] ; then
         exit 0
    fi  
    
#Remove check-aur

rm ~/.config/autostart/check-aur.desktop


