#!/bin/bash

##This create a notify pop-up to warning the user

#This condition is not needed with alpm-hook we can run directly the advice

if [ -f "/usr/bin/yaourt" ] ; then
   
   nohup zenity --warning --title="WARNING" --text="Full access to AUR installed,\nwe open wiki page" &> /dev/null ;
   
   if [ $? == 0 ] ; then
     
      xdg-open https://wiki.manjaro.org/index.php?title=AUR &
   
   fi 

fi
