#!/bin/bash

#Message for user

msg() {
ALL_OFF="\e[1;0m"
BOLD="\e[1;1m"
GREEN="${BOLD}\e[1;32m"
local mesg=$1; shift
printf "
${GREEN}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}" "$@" >&2
}

echo
msg "Warning
-> full access to AUR installed
-> redirect you to our wiki page" ;
echo
     
sleep 3 ;

if [ -n "$SUDO_USER" ]; then
     sudo -u"$SUDO_USER" xdg-open https://wiki.manjaro.org/index.php?title=AUR
else
     xdg-open https://wiki.manjaro.org/index.php?title=AUR
fi

exit 0
