post_install() {
    if [ "$(grep 'GRUB_DISABLE_SUBMENU=y' /etc/default/grub)" == "" ]; then
        echo "GRUB_DISABLE_SUBMENU=y" >> /etc/default/grub
    fi
}

post_upgrade() {

    if [ "$(vercmp $2 20160410)" -lt 0 ] && [ -f /etc/default/tlp ]; then
        sed -i -e 's|#CPU_SCALING_GOVERNOR_ON_AC=ondemand|CPU_SCALING_GOVERNOR_ON_AC=conservative|' /etc/default/tlp
        sed -i -e 's|#CPU_SCALING_GOVERNOR_ON_BAT=ondemand|CPU_SCALING_GOVERNOR_ON_BAT=conservative|' /etc/default/tlp
    fi
}
