#!/bin/sh

utils() {
  if [ -x usr/bin/udevadm ]; then
    usr/bin/udevadm control --reload
  fi
}

# arg 1:  the new package version
post_install() {
  getent group vboxusers >/dev/null || usr/sbin/groupadd -g 108 vboxusers
  utils
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install "$1"
}

# arg 1:  the old package version
post_remove() {
  groupdel vboxusers >/dev/null 2>&1 || true
  utils
}

# vim:set ts=2 sw=2 ft=sh et:
