#!/bin/sh

if [ $(cat /proc/1/comm) = "systemd" ]; then 
	systemctl suspend
else
	dbus-send --system --dest=org.freedesktop.ConsoleKit --type=method_call --print-reply --reply-timeout=2000 /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Suspend boolean:true
fi
