#!/bin/sh

if [ $(cat /proc/1/comm) = "systemd" ]; then
	systemctl reboot
else
	dbus-send --system --print-reply --type=method_call --reply-timeout=2000 --dest=org.freedesktop.ConsoleKit /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart
fi
