#!/bin/sh

#This script disable autostart for pamac-tray and msm_notifier

if [ -f "/etc/xdg/autostart/pamac-tray.desktop" ] ; then
   mv -f /etc/xdg/autostart/pamac-tray.desktop /etc/xdg/autostart/pamac-tray.desktop.save
   echo "Disable pamac-tray autostart in /etc/xdg/autostart"
fi

if [ -f "/etc/xdg/autostart/msm_notifier.desktop" ] ; then
   mv -f /etc/xdg/autostart/msm_notifier.desktop /etc/xdg/autostart/msm_notifier.desktop.save
   echo "Disable msm_notifier autostart in /etc/xdg/autostart"
fi

