EXTRAMODULES='extramodules-4.11-rt-MANJARO'

run_depmode() {
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
}
    
post_install() {
    run_depmode
    echo 'In order to use nvidia module, reboot the system.'
}

post_upgrade() {
    run_depmode
    if  [ "$(vercmp $2 310.19-2)" -lt 0 ]; then
        echo 'If your card is from the 7xxx series or earlier, install nvidia-304xx'
    fi
}

post_remove() {
    run_depmode
}
