post_install() {
  echo "If you are running x86_64, you need the lib32 opt depends for your driver - check that mhwd has it correctly set"
  echo "You can disable the Mesa-library-conflict-workaround (https://bugs.manjaro.org/index.php?do=details&task_id=45) by using \"NOPRELOADWA=1 steam\""
  echo "If you are having problems with the steam license, remove .steam and .local/share/Steam"
}

post_upgrade()
{
    post_install
}
