#!/bin/sh
## This script works around bug #4816 https://github.com/ValveSoftware/steam-for-linux/issues/4816
## that is still present at installation time.

if [ "$(whoami)" = "root" ]
    then
        echo "root is not supported"
        exit 1
fi

export LANG="C"
export LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so'
export LIBGL_DRI3_DISABLE="1"

xdg-open https://github.com/ValveSoftware/steam-for-linux/issues/4816 &

/usr/bin/steam "${@}"

exit 0
